# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rtl_path = QtWidgets.QLineEdit(self.centralwidget)
        self.rtl_path.setObjectName("rtl_path")
        self.horizontalLayout.addWidget(self.rtl_path)
        self.bro_rtl = QtWidgets.QPushButton(self.centralwidget)
        self.bro_rtl.setObjectName("bro_rtl")
        self.horizontalLayout.addWidget(self.bro_rtl)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ass_path = QtWidgets.QLineEdit(self.centralwidget)
        self.ass_path.setObjectName("ass_path")
        self.horizontalLayout_2.addWidget(self.ass_path)
        self.bro_ass = QtWidgets.QPushButton(self.centralwidget)
        self.bro_ass.setObjectName("bro_ass")
        self.horizontalLayout_2.addWidget(self.bro_ass)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.out_path = QtWidgets.QLineEdit(self.centralwidget)
        self.out_path.setObjectName("out_path")
        self.horizontalLayout_3.addWidget(self.out_path)
        self.bro_out = QtWidgets.QPushButton(self.centralwidget)
        self.bro_out.setObjectName("bro_out")
        self.horizontalLayout_3.addWidget(self.bro_out)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.size = QtWidgets.QComboBox(self.centralwidget)
        self.size.setObjectName("size")
        self.size.addItem("")
        self.size.setItemText(0, "")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.size.addItem("")
        self.horizontalLayout_6.addWidget(self.size)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_7.addWidget(self.line_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.mod_rtl = QtWidgets.QLineEdit(self.centralwidget)
        self.mod_rtl.setObjectName("mod_rtl")
        self.verticalLayout_4.addWidget(self.mod_rtl)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.clk_ass = QtWidgets.QLineEdit(self.centralwidget)
        self.clk_ass.setObjectName("clk_ass")
        self.verticalLayout_2.addWidget(self.clk_ass)
        self.add_ass = QtWidgets.QLineEdit(self.centralwidget)
        self.add_ass.setObjectName("add_ass")
        self.verticalLayout_2.addWidget(self.add_ass)
        self.data_ass = QtWidgets.QLineEdit(self.centralwidget)
        self.data_ass.setObjectName("data_ass")
        self.verticalLayout_2.addWidget(self.data_ass)
        self.we_ass = QtWidgets.QLineEdit(self.centralwidget)
        self.we_ass.setObjectName("we_ass")
        self.verticalLayout_2.addWidget(self.we_ass)
        self.oe_ass = QtWidgets.QLineEdit(self.centralwidget)
        self.oe_ass.setObjectName("oe_ass")
        self.verticalLayout_2.addWidget(self.oe_ass)
        self.cs_ass = QtWidgets.QLineEdit(self.centralwidget)
        self.cs_ass.setObjectName("cs_ass")
        self.verticalLayout_2.addWidget(self.cs_ass)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.clk_rtl = QtWidgets.QLineEdit(self.centralwidget)
        self.clk_rtl.setObjectName("clk_rtl")
        self.verticalLayout_3.addWidget(self.clk_rtl)
        self.add_rtl = QtWidgets.QLineEdit(self.centralwidget)
        self.add_rtl.setObjectName("add_rtl")
        self.verticalLayout_3.addWidget(self.add_rtl)
        self.data_rtl = QtWidgets.QLineEdit(self.centralwidget)
        self.data_rtl.setObjectName("data_rtl")
        self.verticalLayout_3.addWidget(self.data_rtl)
        self.we_rtl = QtWidgets.QLineEdit(self.centralwidget)
        self.we_rtl.setObjectName("we_rtl")
        self.verticalLayout_3.addWidget(self.we_rtl)
        self.oe_rtl = QtWidgets.QLineEdit(self.centralwidget)
        self.oe_rtl.setObjectName("oe_rtl")
        self.verticalLayout_3.addWidget(self.oe_rtl)
        self.cs_rtl = QtWidgets.QLineEdit(self.centralwidget)
        self.cs_rtl.setObjectName("cs_rtl")
        self.verticalLayout_3.addWidget(self.cs_rtl)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gen = QtWidgets.QPushButton(self.centralwidget)
        self.gen.setObjectName("gen")
        self.horizontalLayout_4.addWidget(self.gen)
        self.sim = QtWidgets.QPushButton(self.centralwidget)
        self.sim.setObjectName("sim")
        self.horizontalLayout_4.addWidget(self.sim)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout_4.addWidget(self.exit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 368, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SVA-ATCG"))
        self.label_6.setText(_translate("MainWindow", "Automatic TestCases Generator"))
        self.label.setText(_translate("MainWindow", "RTL File:"))
        self.bro_rtl.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Assertions File:"))
        self.bro_ass.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Output File:"))
        self.bro_out.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Memory Size"))
        self.size.setItemText(1, _translate("MainWindow", "64 MB"))
        self.size.setItemText(2, _translate("MainWindow", "128 MB"))
        self.size.setItemText(3, _translate("MainWindow", "256 MB"))
        self.size.setItemText(4, _translate("MainWindow", "512 MB"))
        self.size.setItemText(5, _translate("MainWindow", "1 GB"))
        self.size.setItemText(6, _translate("MainWindow", "2 GB"))
        self.size.setItemText(7, _translate("MainWindow", "4 GB"))
        self.size.setItemText(8, _translate("MainWindow", "8 GB"))
        self.size.setItemText(9, _translate("MainWindow", "16 GB"))
        self.size.setItemText(10, _translate("MainWindow", "32 GB"))
        self.size.setItemText(11, _translate("MainWindow", "64 GB"))
        self.label_18.setText(_translate("MainWindow", "RTL Module Name"))
        self.label_4.setText(_translate("MainWindow", "I/O Ports"))
        self.label_7.setText(_translate("MainWindow", "CLOCK"))
        self.label_8.setText(_translate("MainWindow", "ADDRESS"))
        self.label_9.setText(_translate("MainWindow", "DATA"))
        self.label_10.setText(_translate("MainWindow", "WRITE ENABLE"))
        self.label_11.setText(_translate("MainWindow", "OUTPUT ENABLE"))
        self.label_12.setText(_translate("MainWindow", "CHIP SELECT"))
        self.label_13.setText(_translate("MainWindow", "Assertions"))
        self.label_14.setText(_translate("MainWindow", "RTL"))
        self.gen.setText(_translate("MainWindow", "Generate"))
        self.sim.setText(_translate("MainWindow", "Start Simulation"))
        self.exit.setText(_translate("MainWindow", "Exit"))